name: Deploy Anon Router to Azure

# Запускать пайплайн при каждом пуше в ветку main
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Выделяем временный Linux-сервер от GitHub

    steps:
    # 1. Скачиваем код из репозитория
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Устанавливаем окружение Go
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21' #версия

    # 3. Компилируем бинарник под Linux/amd64 
    - name: Build Go binary
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o anon-router ./cmd/router/

    # 4. Копируем бинарник на сервер во временную папку пользователя
    - name: Copy binary to Azure VM
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        source: "anon-router"
        target: "/home/azureuser/"

    # 5. Перемещаем файл в /opt, выдаем права и перезапускаем сервис
    - name: Restart systemd service
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          # Переносим с правами sudo (так как /opt/anon-router создана root-ом)
          sudo mv /home/azureuser/anon-router /opt/anon-router/anon-router
          sudo chmod +x /opt/anon-router/anon-router
          sudo systemctl restart anon-router
          sleep 2
          sudo systemctl status anon-router --no-pager